#!/usr/bin/ruby
#
# (c) 2015 Konstantin Gredeskoul
# MIT License
#
# Usage:
#       network-scanner network_cidr (--http [timeout seconds] | --ping [num]) --verbose
#    eg:
#       ./network-scanner 172.16.100.1/24 --ping 3"
#       ./network-scanner 192.168.0.0/16 --http 1"
#
require 'ipaddr'

class ScanSubnet
  DEFAULT_PING_COUNT = 3
  DEFAULT_HTTP_TIMEOUT = 1
  DEFAULT_ACTION = '--http'

  class CheckIPviaHTTP
    attr_accessor :timeout
    def initialize(timeout = nil)
      self.timeout = Integer(timeout) rescue false
      self.timeout ||= DEFAULT_HTTP_TIMEOUT
    end
    def check(ip)
      output = `curl -s -I -m #{timeout} http://#{ip}/ 2>&1 | grep HTTP`.chomp
      output !~ /^\s*$/
    end
  end
  class CheckIPviaPing
    attr_accessor :ping_count
    def initialize(ping_count = nil)
      self.ping_count = Integer(ping_count) rescue false
      self.ping_count ||= DEFAULT_PING_COUNT
    end
    def check(ip)
      output = `ping -c #{ping_count} #{ip} 2>/dev/null | grep time= `
      !output.nil?
    end
  end
  attr_accessor :argv, :verbose

  def initialize(argv)
    self.argv = argv
    self.verbose = argv.include?('--verbose') ? true : false
    if argv.include?('--help') || argv.include?('-h')
      usage
      exit 0
    end
  end

  def run!
    input_subnet = argv[0]
    input_action = argv[1] || DEFAULT_ACTION

    action_class = case input_action
                   when "--http"
                     CheckIPviaHTTP.new(argv[2])
                   when "--ping"
                     CheckIPviaPing.new(argv[2])
                   else
                     usage
                     exit 1
                   end

    subnet = validate(input_subnet)
    return if subnet.nil?
    ip_array = subnet.to_range.to_a
    puts "Total IPS: #{ip_array.size}, from #{ip_array.first} to #{ip_array.last}, using #{input_action} to check..."
    ip_array.each do |ip|
      print "checking #{ip}... " if verbose
      result = action_class.check(ip)
      if result
        if verbose
          puts (verbose ? ">> Timeout" : ">> OK")
        else
          puts "\n#{ip} responded\n"
        end
      else
        if verbose
          puts ">> Timeout"
        else
          print "."
        end
      end
    end
  end

  private

  def usage
    puts
    puts "usage: network-scanner subnet [ --http [timeout seconds] | --ping [count] ]"
    puts "                              [ --verbose ] [ --help | -h ]\n\n"
    puts "   eg: network-scanner 172.16.100.1/24 --ping 3 --verbose"
    puts "       network-scanner 192.168.0.0/16  --http 1"
    puts "       network-scanner 192.168.0.0/16  --http"
    puts ""
    puts "       defaults – http, timeout is #{DEFAULT_HTTP_TIMEOUT}, count for ping is #{DEFAULT_PING_COUNT}"
    nil
  end

  def validate(subnet_cidr)
    if subnet_cidr !~ /\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\/[1-3]\d?/
      puts "ERROR: #{subnet_cidr} is not in the CIDR notation"
      usage
    else
      begin
        IPAddr.new subnet_cidr
      rescue Exception => e
        puts "ERROR: IP range can not be parsed. \n\tMust be in CIDR format, ie. 172.16.0.0/24"
        puts e.message
        usage
      end
    end
  end
end

ScanSubnet.new(ARGV).run!
